compressionLevel: mixed

enableColors: true

enableGlobalCache: true

enableImmutableInstalls: false

enableStrictSsl: false

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmmirror.com'

yarnPath: .yarn/releases/yarn-4.5.1.cjs
